services:
  - type: web
    name: paiement-agents-ehcvm3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: FLASK_DEBUG
        value: false
